---
# tasks file for nginx
- name: install nginx
  yum:
    name: nginx
    state: latest
  become: yes

- name: Ensure Nginx Installed
  yum: name=nginx
  notify:
    - save details
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure Nginx Service Running and Enabled
  service: name=nginx state=started enabled=yes
  become: yes

- name: Get Nginx Version
  shell: /usr/sbin/nginx -v 2>&1 | awk -F'/' '{print $2}'
  register: nginx_version
