---
# tasks file for postgresssql
- name: install postgresql
  yum:
    name:
      - postgresql-server
      - postgresql-contrib
    state: present
  become: yes

- name: initial db
  shell: |
    postgresql-setup initdb
  args:
    creates:  /var/lib/pgsql/data/postgresql.conf
  become: yes
  notify:
    - create_user

- name: start_postgres
  systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes
